<style>
    #drop-area {
        border: 2px dashed #ccc;
        border-radius: 20px;
        width: 100%;
        font-family: sans-serif;
        margin: 0 0 20px 0;
        padding: 20px;
    }

    #drop-area.highlight {
        border-color: purple;
    }

    #progress-bar {
        width: 100%;
    }

    #progress-thumbs-bar {
        width: 100%;
    }

    #drop-zone .hidden {
        display: none;
    }
</style>

<div id="drop-zone">
    <div id="drop-area" ondrop="dropHandler(event);" ondragover="dragOverHandler(event);">
        <p>Drag images here to upload</p>
    </div>

    <div class="hidden">
        <span id="progress-text">Upload Progress:</span>
        <progress id="progress-bar" max=100 value=0></progress>

        <span id="progress-thumbs-text">Thumbnails Progress:</span>
        <progress id="progress-thumbs-bar" max=100 value=0></progress>
    </div>
</div>